# Generated by Django 2.2.6 on 2019-10-29 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=4)),
                ('course_name', models.CharField(max_length=100)),
                ('course_prefix', models.CharField(max_length=3)),
                ('subject', models.CharField(max_length=32)),
                ('course_open', models.BooleanField(default=True)),
                ('capicty', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=30)),
                ('enrollee', models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
